CC = gcc
CFLAGS = -Wall -Wextra -std=c99

LOG_ERROR = SPYGLASS_LOG_ERROR_BIT
LOG_WARN = SPYGLASS_LOG_WARNING_BIT
LOG_INFO = SPYGLASS_LOG_INFO_BIT

CFG_COLOR = SPYGLASS_LOG_CFG_USE_COLOR_BIT
CFG_TIME = SPYGLASS_LOG_CFG_SHOW_TIME_BIT
CFG_FILE = SPYGLASS_LOG_CFG_SHOW_FILE_BIT
CFG_FUNC = SPYGLASS_LOG_CFG_SHOW_FUNC_BIT
CFG_LINE = SPYGLASS_LOG_CFG_SHOW_LINE_BIT

DEBUG_LEVELS = "($(LOG_ERROR)|$(LOG_WARN)|$(LOG_INFO))"
DEBUG_FLAGS = "($(CFG_COLOR)|$(CFG_TIME)|$(CFG_FILE)|$(CFG_FUNC)|$(CFG_LINE))"

TEST_LEVELS = "($(LOG_ERROR)|$(LOG_WARN))"
TEST_FLAGS = "($(CFG_TIME)|$(CFG_FILE)|$(CFG_FUNC)|$(CFG_LINE))"

SRC = spyglass_log.c example.c
OBJ = $(SRC:.c=.o)
TARGET = example

all: release
debug: CFLAGS += -D SPYGLASS_CONFIG_FLAGS=$(DEBUG_FLAGS) \
                 -D SPYGLASS_CONFIG_LEVELS=$(DEBUG_LEVELS)
debug: $(TARGET)

test: CFLAGS += -D SPYGLASS_CONFIG_FLAGS=$(TEST_FLAGS) \
                 -D SPYGLASS_CONFIG_LEVELS=$(TEST_LEVELS)
test: $(TARGET)
release: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(TARGET)

.PHONY: all debug test release clean